"""Centralized metric knowledge registry for Trend Lens."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MetricDefinition:
    """User-facing explanation for a metric or indicator."""

    key: str
    label: str
    category: str
    plain_english_definition: str
    why_it_matters: str
    interpretation_ranges: tuple[str, ...]
    good_to_know: str
    unit_type: str
    short_label: str | None = None
    formula_hint: str | None = None
    example_interpretation: str | None = None


METRIC_DEFINITIONS: dict[str, MetricDefinition] = {
    "price_vs_50dma": MetricDefinition(
        key="price_vs_50dma",
        label="Price vs 50DMA",
        short_label="near-term trend check",
        category="technical",
        plain_english_definition="Checks whether price is above or below its 50-day trend line.",
        why_it_matters="It is a quick read on short-to-medium term trend health.",
        interpretation_ranges=(
            "Above the 50DMA often suggests the near-term trend is still healthy.",
            "Below the 50DMA can suggest short-term momentum is cooling.",
        ),
        good_to_know="Short dips below the 50DMA are common even in healthy uptrends.",
        formula_hint="Current price / 50DMA - 1",
        unit_type="percent",
        example_interpretation="A stock 4% above the 50DMA is usually in a healthier position than one 6% below it.",
    ),
    "price_vs_200dma": MetricDefinition(
        key="price_vs_200dma",
        label="Price vs 200DMA",
        short_label="long-term trend check",
        category="technical",
        plain_english_definition="Checks whether price is above or below its 200-day trend line.",
        why_it_matters="It is a common long-term trend check.",
        interpretation_ranges=(
            "Above the 200DMA often suggests the primary trend is still constructive.",
            "Below the 200DMA can suggest the longer-term trend is under pressure.",
        ),
        good_to_know="Some stocks can stay below the 200DMA for long stretches in weak cycles.",
        formula_hint="Current price / 200DMA - 1",
        unit_type="percent",
    ),
    "sma_50": MetricDefinition(
        key="sma_50",
        label="50-day moving average",
        short_label="50DMA",
        category="technical",
        plain_english_definition="The average closing price over the last 50 trading days.",
        why_it_matters="It smooths out daily noise and gives a cleaner read on the medium-term trend.",
        interpretation_ranges=(
            "A rising 50DMA often suggests improving trend strength.",
            "A flat or falling 50DMA can suggest momentum is fading.",
        ),
        good_to_know="Moving averages lag price because they are backward-looking by design.",
        unit_type="currency",
    ),
    "sma_200": MetricDefinition(
        key="sma_200",
        label="200-day moving average",
        short_label="200DMA",
        category="technical",
        plain_english_definition="The average closing price over the last 200 trading days.",
        why_it_matters="It is one of the most common long-term trend anchors used by investors.",
        interpretation_ranges=(
            "A rising 200DMA often suggests the long-term trend is still healthy.",
            "A falling 200DMA can suggest the bigger picture is weakening.",
        ),
        good_to_know="Because it is very slow-moving, it is more useful for trend context than precise entries.",
        unit_type="currency",
    ),
    "dist_from_50dma": MetricDefinition(
        key="dist_from_50dma",
        label="Distance from 50DMA",
        short_label="extension vs 50DMA",
        category="technical",
        plain_english_definition="Measures how far price is from the 50DMA.",
        why_it_matters="It helps spot healthy pullbacks versus stretched moves.",
        interpretation_ranges=(
            "Small positive readings can suggest a healthy trend.",
            "Too far above can suggest extension.",
            "Near or just below the 50DMA can sometimes mark a pullback entry zone.",
        ),
        good_to_know="High-volatility stocks can live farther from the 50DMA than steadier names.",
        formula_hint="Current price / 50DMA - 1",
        unit_type="percent",
    ),
    "dist_from_200dma": MetricDefinition(
        key="dist_from_200dma",
        label="Distance from 200DMA",
        short_label="extension vs 200DMA",
        category="technical",
        plain_english_definition="Measures how far price is from the 200DMA.",
        why_it_matters="It helps show long-term extension versus the stock’s base trend.",
        interpretation_ranges=(
            "Moderate positive readings can be healthy in sustained uptrends.",
            "Very large positive readings can suggest the stock is extended.",
            "Negative readings can suggest the stock is below its long-term trend.",
        ),
        good_to_know="A stock can look extended versus the 200DMA and still keep climbing in strong momentum phases.",
        formula_hint="Current price / 200DMA - 1",
        unit_type="percent",
    ),
    "rsi_14": MetricDefinition(
        key="rsi_14",
        label="RSI (14)",
        short_label="momentum heat check",
        category="technical",
        plain_english_definition="RSI measures whether recent price momentum looks overheated or washed out.",
        why_it_matters="It can help flag healthy momentum, extension, or oversold conditions.",
        interpretation_ranges=(
            "Below 30 can suggest oversold conditions.",
            "Around 40 to 60 is often a healthier range in ongoing trends.",
            "Above 70 can suggest the stock is extended.",
        ),
        good_to_know="Strong stocks can stay overbought longer than expected, so RSI should not be used alone.",
        unit_type="ratio",
        example_interpretation="An RSI of 75 can mean strong momentum, but it also raises the odds of a pause or pullback.",
    ),
    "macd": MetricDefinition(
        key="macd",
        label="MACD",
        short_label="momentum trend line",
        category="technical",
        plain_english_definition="MACD compares short-term and medium-term trend speed using moving averages.",
        why_it_matters="It helps show whether momentum is improving or fading.",
        interpretation_ranges=(
            "Above the signal line often suggests improving momentum.",
            "Below the signal line can suggest weakening momentum.",
        ),
        good_to_know="MACD is best used as a confirmation tool, not by itself.",
        unit_type="ratio",
    ),
    "macd_signal": MetricDefinition(
        key="macd_signal",
        label="MACD signal line",
        short_label="momentum trigger line",
        category="technical",
        plain_english_definition="The signal line is a smoothed version of MACD used to judge momentum shifts.",
        why_it_matters="Crosses above or below this line can flag improving or weakening momentum.",
        interpretation_ranges=(
            "MACD above signal often suggests improving momentum.",
            "MACD below signal can suggest momentum is fading.",
        ),
        good_to_know="Signal-line crosses can whipsaw in choppy markets.",
        unit_type="ratio",
    ),
    "macd_histogram": MetricDefinition(
        key="macd_histogram",
        label="MACD histogram",
        short_label="momentum spread",
        category="technical",
        plain_english_definition="Shows the gap between MACD and its signal line.",
        why_it_matters="It gives a quicker read on momentum acceleration or slowdown.",
        interpretation_ranges=(
            "Positive histogram bars often suggest bullish momentum pressure.",
            "Negative bars can suggest weakening or bearish momentum pressure.",
        ),
        good_to_know="The histogram is helpful for momentum direction, but it can turn quickly in volatile stocks.",
        unit_type="ratio",
    ),
    "avg_volume_20": MetricDefinition(
        key="avg_volume_20",
        label="20-day average volume",
        short_label="20D avg volume",
        category="technical",
        plain_english_definition="Average daily volume over the last 20 trading sessions.",
        why_it_matters="It gives a baseline for judging whether current trading activity is strong or weak.",
        interpretation_ranges=(
            "Higher-than-average volume can confirm stronger participation.",
            "Lighter volume can make a move look less convincing.",
        ),
        good_to_know="Volume patterns differ a lot by market cap, ETF type, and seasonal trading conditions.",
        unit_type="shares",
    ),
    "volume_ratio": MetricDefinition(
        key="volume_ratio",
        label="Volume vs 20-day average",
        short_label="participation check",
        category="technical",
        plain_english_definition="Compares current volume to the recent 20-day average volume.",
        why_it_matters="It helps show whether the current move has enough participation behind it.",
        interpretation_ranges=(
            "Around 1.0x is roughly normal volume.",
            "Clearly above 1.0x often suggests stronger confirmation.",
            "Well below 1.0x can suggest a move has weaker backing.",
        ),
        good_to_know="Light volume is not always bad, but stronger moves usually look better with stronger participation.",
        formula_hint="Current volume / 20-day average volume",
        unit_type="ratio",
    ),
    "trend_alignment": MetricDefinition(
        key="trend_alignment",
        label="50DMA vs 200DMA",
        short_label="trend alignment",
        category="technical",
        plain_english_definition="Checks whether the 50DMA is above or below the 200DMA.",
        why_it_matters="It is a quick read on whether medium-term and long-term trends agree.",
        interpretation_ranges=(
            "50DMA above 200DMA often suggests constructive trend alignment.",
            "50DMA below 200DMA can suggest a weaker broader trend.",
        ),
        good_to_know="Trend alignment changes slowly, so it is more useful for context than for precise entries.",
        unit_type="text",
    ),
    "trailing_pe": MetricDefinition(
        key="trailing_pe",
        label="Trailing P/E",
        short_label="price vs past earnings",
        category="fundamental",
        plain_english_definition="Compares stock price to earnings from the last 12 months.",
        why_it_matters="It is a common first pass on valuation.",
        interpretation_ranges=(
            "Lower values can look cheaper.",
            "Higher values can still be reasonable if growth is strong.",
        ),
        good_to_know="Sector context matters a lot; different industries naturally trade at different P/E ranges.",
        unit_type="ratio",
    ),
    "forward_pe": MetricDefinition(
        key="forward_pe",
        label="Forward P/E",
        short_label="price vs expected earnings",
        category="fundamental",
        plain_english_definition="Compares stock price to expected earnings over the next year.",
        why_it_matters="It gives a more forward-looking valuation read than trailing P/E.",
        interpretation_ranges=(
            "Lower values can look more attractive if forecasts are realistic.",
            "High values can still be justified when growth expectations are strong.",
        ),
        good_to_know="Forward estimates can move quickly when analyst expectations change.",
        unit_type="ratio",
    ),
    "peg_ratio": MetricDefinition(
        key="peg_ratio",
        label="PEG Ratio",
        short_label="valuation vs growth",
        category="fundamental",
        plain_english_definition="PEG compares P/E to expected growth so valuation can be viewed in growth context.",
        why_it_matters="It helps compare valuation to expected growth.",
        interpretation_ranges=(
            "Lower is generally better relative to growth.",
            "Above 2 can suggest growth may already be well priced in.",
        ),
        good_to_know="PEG values are often noisy or missing when analyst estimates are unstable.",
        unit_type="ratio",
    ),
    "return_on_equity": MetricDefinition(
        key="return_on_equity",
        label="Return on Equity",
        short_label="ROE",
        category="fundamental",
        plain_english_definition="ROE measures how effectively a company turns shareholder capital into profit.",
        why_it_matters="Higher ROE can suggest better capital efficiency and business quality.",
        interpretation_ranges=(
            "Higher can be better.",
            "Low ROE can suggest weaker profitability or capital efficiency.",
        ),
        good_to_know="ROE can be inflated by heavy leverage, so it should be read alongside debt metrics.",
        unit_type="percent",
    ),
    "debt_to_equity": MetricDefinition(
        key="debt_to_equity",
        label="Debt to Equity",
        short_label="balance-sheet leverage",
        category="fundamental",
        plain_english_definition="Compares company debt to shareholder equity.",
        why_it_matters="Lower ratios often mean less balance-sheet risk and more flexibility.",
        interpretation_ranges=(
            "Lower generally means less leverage risk.",
            "Higher can be fine in capital-intensive sectors, but context matters.",
        ),
        good_to_know="Banks, utilities, and industrial businesses often carry more debt than software companies.",
        unit_type="ratio",
    ),
    "revenue_growth": MetricDefinition(
        key="revenue_growth",
        label="Revenue growth",
        short_label="top-line growth",
        category="fundamental",
        plain_english_definition="Measures how fast the company’s sales are growing.",
        why_it_matters="Sales growth is often the cleanest first check of business momentum.",
        interpretation_ranges=(
            "Positive growth is generally supportive.",
            "Stronger double-digit growth can be especially attractive for growth companies.",
        ),
        good_to_know="Very high revenue growth is not enough by itself if margins or cash flow are poor.",
        unit_type="percent",
    ),
    "earnings_growth": MetricDefinition(
        key="earnings_growth",
        label="Earnings growth",
        short_label="bottom-line growth",
        category="fundamental",
        plain_english_definition="Measures how fast earnings per share are growing.",
        why_it_matters="It helps show whether growth is making it through to the bottom line.",
        interpretation_ranges=(
            "Positive growth is generally supportive.",
            "Very weak or negative growth can pressure valuation support.",
        ),
        good_to_know="Earnings can swing more sharply than revenue because margins and one-time items can distort the picture.",
        unit_type="percent",
    ),
    "free_cash_flow": MetricDefinition(
        key="free_cash_flow",
        label="Free cash flow",
        short_label="cash left after investment",
        category="fundamental",
        plain_english_definition="Cash left after the business covers operating needs and capital spending.",
        why_it_matters="Positive free cash flow can support durability and strategic flexibility.",
        interpretation_ranges=(
            "Positive is generally healthier than negative.",
            "Larger positive cash flow can support business flexibility.",
        ),
        good_to_know="Free cash flow can be lumpy, especially for seasonal or investment-heavy businesses.",
        unit_type="currency",
    ),
    "operating_cash_flow": MetricDefinition(
        key="operating_cash_flow",
        label="Operating cash flow",
        short_label="cash from operations",
        category="fundamental",
        plain_english_definition="Cash generated by the company’s core operations before capital spending.",
        why_it_matters="It helps show whether the business is generating real cash from day-to-day operations.",
        interpretation_ranges=(
            "Positive is generally supportive.",
            "Growing operating cash flow can suggest improving business quality.",
        ),
        good_to_know="A company can have strong operating cash flow but weaker free cash flow if it is investing heavily.",
        unit_type="currency",
    ),
    "gross_margin": MetricDefinition(
        key="gross_margin",
        label="Gross margin",
        short_label="basic profitability",
        category="fundamental",
        plain_english_definition="Shows how much revenue is left after direct costs of producing goods or services.",
        why_it_matters="Higher gross margins can suggest better pricing power or a stronger business model.",
        interpretation_ranges=(
            "Higher is often better.",
            "Thin margins can leave less room for error if costs rise.",
        ),
        good_to_know="Gross margin norms vary sharply across sectors.",
        unit_type="percent",
    ),
    "operating_margin": MetricDefinition(
        key="operating_margin",
        label="Operating margin",
        short_label="core business profitability",
        category="fundamental",
        plain_english_definition="Shows how much revenue is left after operating expenses.",
        why_it_matters="It is a useful read on core business profitability.",
        interpretation_ranges=(
            "Higher often suggests a more efficient or stronger business model.",
            "Lower margins can limit resilience if growth slows.",
        ),
        good_to_know="Operating margin is especially helpful when comparing peers in the same industry.",
        unit_type="percent",
    ),
    "profit_margin": MetricDefinition(
        key="profit_margin",
        label="Profit margin",
        short_label="bottom-line profitability",
        category="fundamental",
        plain_english_definition="Shows how much of each dollar of revenue turns into net profit.",
        why_it_matters="It shows how much of revenue survives all the way to net profit.",
        interpretation_ranges=(
            "Higher margins often suggest stronger business quality.",
            "Very thin margins can make earnings fragile.",
        ),
        good_to_know="One-time tax or accounting items can temporarily distort profit margins.",
        unit_type="percent",
    ),
    "data_completeness": MetricDefinition(
        key="data_completeness",
        label="Data completeness",
        short_label="coverage quality",
        category="fundamental",
        plain_english_definition="Shows how much of the expected fundamental data was actually available.",
        why_it_matters="Lower completeness means the model should be less confident in the fundamental read.",
        interpretation_ranges=(
            "Higher completeness usually supports more confidence.",
            "Lower completeness should reduce conviction, not be ignored.",
        ),
        good_to_know="Yahoo Finance coverage varies a lot across tickers, ETFs, and international listings.",
        unit_type="percent",
    ),
    "confidence": MetricDefinition(
        key="confidence",
        label="Confidence",
        short_label="conviction label",
        category="fundamental",
        plain_english_definition="A blended read of how complete the data is and how well the signals align.",
        why_it_matters="It shows how much trust to place in the read, separate from whether the score is high or low.",
        interpretation_ranges=(
            "High means good alignment and good data coverage.",
            "Medium means usable but mixed.",
            "Low means sparse data or weak alignment should reduce conviction.",
        ),
        good_to_know="Confidence is about trust in the read, not a prediction of return.",
        unit_type="text",
    ),
    "current_position_value": MetricDefinition(
        key="current_position_value",
        label="Current position value",
        short_label="position size now",
        category="position",
        plain_english_definition="The current market value of the shares you own.",
        why_it_matters="It is the starting point for allocation math and sizing decisions.",
        interpretation_ranges=(
            "Larger values mean this stock is already carrying more weight in the portfolio.",
        ),
        good_to_know="This value changes with the stock price even if you do not trade.",
        formula_hint="Shares owned × current price",
        unit_type="currency",
    ),
    "current_allocation_pct": MetricDefinition(
        key="current_allocation_pct",
        label="Current allocation",
        short_label="portfolio weight",
        category="position",
        plain_english_definition="Shows what percentage of your portfolio this position currently represents.",
        why_it_matters="It tells you whether the position is small, on target, or getting too large.",
        interpretation_ranges=(
            "Below your cap usually means there is still room to add.",
            "Near or above your cap can suggest more caution.",
        ),
        good_to_know="Allocation math is only as good as the portfolio value you provide.",
        formula_hint="Current position value / total portfolio value",
        unit_type="percent",
    ),
    "max_position_cap": MetricDefinition(
        key="max_position_cap",
        label="Max position cap",
        short_label="hard sizing limit",
        category="position",
        plain_english_definition="The maximum allocation you want this position to reach.",
        why_it_matters="It acts as a guardrail so one idea does not become too large.",
        interpretation_ranges=(
            "A lower cap keeps single-position risk lower.",
            "A higher cap allows more concentration.",
        ),
        good_to_know="The right cap depends on conviction, diversification goals, and your tolerance for volatility.",
        unit_type="percent",
    ),
    "target_position_size": MetricDefinition(
        key="target_position_size",
        label="Target position size",
        short_label="desired allocation",
        category="position",
        plain_english_definition="An optional softer target below your hard max cap.",
        why_it_matters="It helps distinguish between a position you are still building and one already near your desired size.",
        interpretation_ranges=(
            "Below target can support continued building.",
            "Near target often suggests more patience or smaller adds.",
        ),
        good_to_know="The target is optional and should usually sit below the hard cap.",
        unit_type="percent",
    ),
    "remaining_room_to_add": MetricDefinition(
        key="remaining_room_to_add",
        label="Remaining room to add",
        short_label="space under the cap",
        category="position",
        plain_english_definition="The dollar amount you can still add before reaching your max position cap.",
        why_it_matters="It shows whether you have real allocation capacity left.",
        interpretation_ranges=(
            "Large remaining room can support adding.",
            "Very small remaining room usually argues for smaller or no adds.",
        ),
        good_to_know="Room under the cap does not automatically mean you should buy; the setup still matters.",
        unit_type="currency",
    ),
    "cash_limited_add_amount": MetricDefinition(
        key="cash_limited_add_amount",
        label="Cash-limited add amount",
        short_label="usable buying power now",
        category="position",
        plain_english_definition="The smaller of your available cash and the remaining room under your cap.",
        why_it_matters="It shows what you can realistically deploy right now without breaking your size rules.",
        interpretation_ranges=(
            "Higher values mean more immediate capacity to add.",
            "Zero means either no cash or no room under the cap.",
        ),
        good_to_know="This is a practical sizing number, not a recommendation by itself.",
        unit_type="currency",
    ),
    "estimated_shares_can_add": MetricDefinition(
        key="estimated_shares_can_add",
        label="Estimated shares can add",
        short_label="shares you could buy now",
        category="position",
        plain_english_definition="Estimated whole shares you could add right now based on cash and cap room.",
        why_it_matters="It turns position math into a practical next step.",
        interpretation_ranges=(
            "Higher numbers mean more room to build.",
            "Zero means you cannot add without changing cash or sizing constraints.",
        ),
        good_to_know="This assumes whole shares and ignores taxes, slippage, and trading fees.",
        unit_type="shares",
    ),
    "unrealized_gain_loss_dollars": MetricDefinition(
        key="unrealized_gain_loss_dollars",
        label="Unrealized gain/loss $",
        short_label="paper gain/loss",
        category="position",
        plain_english_definition="The estimated dollar gain or loss on the shares you already hold.",
        why_it_matters="It helps show whether you are pressing a winner, averaging down, or making a fresh decision.",
        interpretation_ranges=(
            "Positive means the position is above your cost basis.",
            "Negative means the position is below your cost basis.",
        ),
        good_to_know="This number depends on having a usable average cost basis.",
        unit_type="currency",
    ),
    "unrealized_gain_loss_pct": MetricDefinition(
        key="unrealized_gain_loss_pct",
        label="Unrealized gain/loss %",
        short_label="paper return",
        category="position",
        plain_english_definition="The estimated percentage gain or loss versus your average cost basis.",
        why_it_matters="It helps frame whether the position is working, stretched, or deeply underwater.",
        interpretation_ranges=(
            "Positive means you are above cost basis.",
            "Negative means you are below cost basis.",
        ),
        good_to_know="A big gain can justify more caution if the stock is also technically extended.",
        unit_type="percent",
    ),
}
